version: '3.9'

services:
  postgresql:
    image: postgres:14.10-alpine
    container_name: postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ~/apps/postgresql/:/var/lib/postgresql/data
